name: Egg

flownet:
  data_source:
    simulation:
      input_case: ../input_model/egg/EGG_MODEL_ECL
      vectors:
        WBHP:
          rel_error: 0.005
          min_error: 1
        WOPR:
          rel_error: 0.01
          min_error: 1
  phases:
    - oil
    - water
  cell_length: 10
  additional_flow_nodes: 50
  additional_node_candidates: 1000
  hull_factor: 1.2
  random_seed: 999
  perforation_handling_strategy: bottom_point
  fast_pyscal: true
  training_set_fraction: 0.8
  fault_tolerance: 0.1
  hyperopt:
    n_runs: 10
    mode: tpe
    loss:
      keys: ["WOPR:PROD", "WWPR:PROD"]
      factors: [0.5, 0.5]
      metric: RMSE
ert:
  static_include_files: ./egg_static
  realizations:
    num_realizations: 250
    required_success_percent: 80
    max_runtime: 600
  queue:
    system: LOCAL
    name: mr
    max_running: 4
  ensemble_weights:
    - 4
    - 3
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
  analysis:
    metric: [RMSE, MAE]
    quantity: [WOPR:PROD, WWPR:PROD]
    start: 2011-01-01
    end: 2016-06-01
    outfile: analysis_metrics_iteration
model_parameters:
  permeability:
    min: 10
    max: 10000
  porosity:
    min: 0.01
    max: 0.35
  bulkvolume_mult:
    min: ["UNIFORM", 1, 2]
    max: 20
  relative_permeability:
    scheme: ["UNIFORM_CHOICE", "global", "individual"]
    regions:
      - id: None
        swirr:
          min: 0.01
          max: 0.2
        swl:
          min: 0.01
          max: 0.2
        swcr:
          min: 0.1
          max: 0.3
        sorw:
          min: 0.05
          max: 0.3
        krwend:
          min: 0.5
          max: 0.7
        kroend:
          min: 0.6
          max: 0.9
        nw:
          min: 1.5
          max: 4.5
        now:
          min: 2.5
          max: 5.5
  equil:
    regions:
      - id: None
        datum_depth: 4000
        datum_pressure:
          min: 380
          max: 420
        owc_depth:
          min: 4980
          max: 5020
