name: Egg

ert:
  pred_schedule_file: ./trivial_prediction_schedule.sch
  static_include_files: ./egg_static
  realizations:
    num_realizations: 250
    required_success_percent: 80
    max_runtime: 300
  queue:
    system: LOCAL
    name: mr
    max_running: 4

export:
  csv_outfile: egg_flownet_predictions
  quantity: [WOPR, WWPR, WBHP]
  end_date: 2021-05-01
