name: Egg

ert:
  pred_schedule_file: ./trivial_prediction_schedule.sch
  static_include_files: ./egg_static
  realizations:
    num_realizations: 250
    required_success_percent: 80
    max_runtime: 300
  queue:
    system: LOCAL
    name: mr
    max_running: 10
